version: '3'

volumes:
  pg_data:
  code:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: 'file_transfer_redis'
    command: redis-server
    ports:
      - '6379:6379'
  backend:
    build: ./file_transfer_api/
    env_file: .env
    volumes:
      - static:/static
      - code:/backend
    depends_on:
      - db
  celery:
    build: .
    container_name: 'file_transfer_celery'
    command: celery -A core worker -B
    volumes:
      - code:/code
    links:
      - redis
    depends_on:
      - backend
      - redis
