# Generated by Django 4.2.2 on 2023-06-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_transfer", "0002_alter_file_file_alter_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="processed",
            field=models.IntegerField(default=0),
        ),
    ]
